### ISSUE TITLE
Create 301 redirect to HTTPS

### ISSUE THREAD

**Issue by rossey** [phphants/php-south-coast-2015#7]
For www. and cfp. subdomains

**Comment by rossey** [comment]
I think you need to also tell CFP that it's running over HTTPS

**Comment by asgrim** [comment]
I'm already working on it, it doesn't work properly yet because of reasons

**Comment by rossey** [comment]
Reasons are :hankey: :(

**Comment by asgrim** [comment]
I think this is working now. I have not enabled it on the main site (we don't really need it, it is just a static site), just on the CFP site, but the CFP site forces HTTPS now for any "secure" required pages

**Comment by rossey** [comment]
Can you HTTPS the whole lot? There's not much point if you can lift the session over HTTP

**Comment by asgrim** [comment]
it is linked to from the website via HTTPS, but without changing OpenCFP itself I can't stop people going directly to http://cfp.phpsouthcoast.co.uk/

**Comment by dave1010** [comment]
@asgrim *.phpsouthcoast.co.uk should be over HTTPS, otherwise you can set cookies on an HTTP subdomain.

**Comment by asgrim** [comment]
looks like we can't: https://github.com/isaacs/github/issues/156 (HT @fullybaked)

Specifically: https://github.com/isaacs/github/issues/156#issuecomment-60453315 this is our exact issue

**Comment by dave1010** [comment]
CF can proxy HTTP, so this should work fine. GH pages doesn't need to know about SSL. This protects the user between themselves and CF but not CF & GH pages.

CF call this "Flexible SSL": https://support.cloudflare.com/hc/en-us/articles/200170416-What-do-the-SSL-options-Off-Flexible-Full-Full-Strict-mean-

**Comment by asgrim** [comment]
It seems to be all-or-nothing - I can't enable Full SSL for CFP (which it requires to work with OpenCFP) and Flexible SSL on the main site :/

**Comment by asgrim** [comment]
i.e. If we don't have Full SSL on the CFP, then OpenCFP keeps redirecting back to http://

**Comment by rossey** [comment]
ok. thanks for trying @asgrim! :)
