### ISSUE TITLE
Footer social media icons don't work in FF on Ubuntu

### ISSUE THREAD

**Issue by rossey** [phphants/php-south-coast-2015#8]
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0

**Comment by asgrim** [comment]
![worksforme](https://cloud.githubusercontent.com/assets/496145/5356101/5d3d0cda-7f91-11e4-90c4-b1ba49f3682a.png)

**Comment by asgrim** [comment]
Seems to work OK?

**Comment by lboynton** [comment]
Yep I don't see a problem with them :confused:

**Comment by davidyell** [comment]
It would be nice to clarify "not working". My assumption is that clicking them takes me to Facebook or Twitter, in which regard they are linking okay for me.

**Comment by rossey** [comment]
OK. Looks like AdBlock Plus is blocking the social media images
